// Lidské popisky SOD placeholderů. Čistý modul (bez server importů), aby ho
// mohl použít i klientský GenerateSodModal i serverové routy.
export const SOD_PLACEHOLDER_LABELS: Record<string, string> = {
  klient_jmeno: 'Jméno klienta',
  klient_adresa: 'Adresa klienta',
  klient_email: 'E-mail klienta',
  klient_telefon: 'Telefon klienta',
  klient_ico: 'IČO klienta',
  klient_dic: 'DIČ klienta',
  kontaktni_osoba: 'Kontaktní osoba',
  kontaktni_telefon: 'Kontaktní telefon',
  predmet: 'Předmět díla',
  adresa_dila: 'Adresa díla',
  obchodnik: 'Obchodník',
  termin_realizace: 'Termín realizace',
  termin_prevzeti: 'Termín předání',
  pocet_dni_realizace: 'Počet dní realizace',
  hodnota_zalohy: 'Výše zálohy',
  zaloha_splatnost: 'Splatnost zálohy (dní)',
  konecna_cena: 'Cena bez DPH',
  cena_s_dph: 'Cena s DPH',
  dph_sazba: 'Sazba DPH',
  kod_op: 'Kód OP',
  organizace: 'Název organizace',
  org_sidlo: 'Sídlo organizace',
  org_ico: 'IČO organizace',
  org_dic: 'DIČ organizace',
  zmena_term: 'Podmínka změny termínu',
  technologie: 'Technologie',
}
