-- Interní podpis SOD za zhotovitele (zmocněnci) před odesláním klientovi
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "podepisujeSmlouvy" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "zhotovitelPodpisSvg" TEXT;
ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "zhotovitelPodepsano" TIMESTAMP(3);
ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "zhotovitelPodepsalJmeno" TEXT;
ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "zhotovitelPodepsalId" TEXT;
ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "zhotovitelTextHash" TEXT;
ALTER TABLE "sod" ADD COLUMN IF NOT EXISTS "podpisZadost" JSONB;

ALTER TYPE "SodStav" ADD VALUE IF NOT EXISTS 'K_INTERNIMU_PODPISU' BEFORE 'ODESLANO';
ALTER TYPE "SodUdalostTyp" ADD VALUE IF NOT EXISTS 'PODPIS_VYZADAN' BEFORE 'ODESLANO';
ALTER TYPE "SodUdalostTyp" ADD VALUE IF NOT EXISTS 'PODEPSANO_ZHOTOVITELEM' BEFORE 'ODESLANO';
